services:
  web:
    image: ghcr.io/gamero-g/lpgroove:latest
    build: .
    container_name: lpgroove-web
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: lpg_08_26
      DB_USERNAME: miapp_user
      DB_PASSWORD: miapp_pass

  db:
    image: mariadb:11
    container_name: lpgroove-db
    environment:
      MARIADB_DATABASE: lpg_08_26
      MARIADB_USER: miapp_user
      MARIADB_PASSWORD: miapp_pass
      MARIADB_ROOT_PASSWORD: root_pass_123
    volumes:
      - /mnt/user/appdata/lpgroove/db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: lpgroove-phpmyadmin
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
